project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from . import views
# from recipes.views import home

app_name = 'recipes'

urlpatterns = [
    path('', views.home, name="home"),
    path('recipes/<int:id>/', views.recipes, name="recipe"),
    path('recipes/category/<int:category_id>/', views.category, name="category")
]

recipes/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=65)
    
    def __str__ (self): 
        return self.name
        

class Recipe(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField()
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=65)
    preparation_steps = models.TextField()
    preapration_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(upload_to='recipes/covers/%Y/%m/%d/', blank=True, default='')
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True)
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True
    )
    
    def __str__(self):
        return self.title
    

recipes/views.py
from django.shortcuts import render
from utils.recipes.factory import make_recipe
from .models import Recipe


def home(request):
    recipe = Recipe.objects.filter(is_published=True).order_by('-id')
    return render(request, 'recipes/pages/home.html', context={
        'recipes': recipe,
    })
    
def category(request, category_id):
    recipe = Recipe.objects.filter(category__id=category_id, is_published=True).order_by('-id')
    return render(request, 'recipes/pages/category.html', context={
        'recipes': recipe,
    })
    
def recipes(request, id):
    return render(request, 'recipes/pages/recipe-views.html', context={
        'recipe': make_recipe(),
        'is_datail_page': True
            }
)
    

recipes/templates/recipes/pages/category.html
{% extends 'global/base.html' %} 

{% block title%}Category | {%endblock title%}
{%block content%}
<div class="main-content main-content-list container">
  {% for recipe in recipes %} 
  
      {% include 'recipes/partials/recipe.html'%}
  
  {%endfor%}
</div>
{%endblock content%}

recipes/templates/recipes/pages/home.html
{% extends 'global/base.html' %} 
{%block content%}
<div class="main-content main-content-list container">
  
  {% for recipe in recipes %} 
  
      {% include 'recipes/partials/recipe.html'%}
  
  {%endfor%}
</div>
{%endblock content%}

recipes/templates/recipes/pages/recipe-views.html
{% extends 'global/base.html' %}
{% block title %}Altera {% endblock title %} Recipe
{% block content %}
<div class="main-content main-content-detail container">
    {% include 'recipes/partials/recipe.html' %}
</div>
{%endblock content%}

recipes/templates/recipes/partials/footer.html
<footer class="main-footer">
  <div class="developer">
    <a href="https://github.com/wendellast" target="_blank" rel="no-referrer"
      >Wendellast</a
    >
  </div>

  <div class="powered">
    <a
      href="https://github.com/wendellast/Django"
      target="_blank"
      rel="no-referrer"
      >GitHub</a
    >
  </div>
</footer>

recipes/templates/recipes/partials/head.html
{% load static %}

<meta charset="UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
  integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
  crossorigin="anonymous"
  referrerpolicy="no-referrer"
/>
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/brands.min.css"
  integrity="sha512-9YHSK59/rjvhtDcY/b+4rdnl0V4LPDWdkKceBl8ZLF5TB6745ml1AfluEU6dFWqwDw9lPvnauxFgpKvJqp7jiQ=="
  crossorigin="anonymous"
  referrerpolicy="no-referrer"
/>
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/solid.min.css"
  integrity="sha512-yDUXOUWwbHH4ggxueDnC5vJv4tmfySpVdIcN1LksGZi8W8EVZv4uKGrQc0pVf66zS7LDhFJM7Zdeow1sw1/8Jw=="
  crossorigin="anonymous"
  referrerpolicy="no-referrer"
/>
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link
  href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@700&display=swap"
  rel="stylesheet"
/>
<!-- Static -->
<link rel="stylesheet" href="{% static 'recipes/css/style.css' %}">

<link rel="stylesheet" href="{% static 'global/css/global-style.css'%}">

recipes/templates/recipes/partials/header.html
<header class="main-header-container">
  <div class="main-header container">
    <h1>
      <a class="main-logo" href="{% url 'recipes:home' %}"
        ><i class="fa-brands fa-github fa-shake main-logo-icon"></i>
        <span class="main-logo-text">Recipes {{name}}</span>
      </a>
    </h1>
  </div>
</header>

recipes/templates/recipes/partials/recipe.html
<div class="recipe-list-item recipe">
  {% if recipe.cover %}
    <div class="recipes-cover">
      <a href=" {% url 'recipes:recipe' recipe.id %}">
      <img src="{{recipe.cover.url}}" alt="temp" />
    </a>
    </div>
  {% endif%}
  <div class="recipe-title-container">
    <a href=" {% url 'recipes:recipe' recipe.id %}">
    <h2 class="recipe-title">{{ recipe.title }}</h2>
    </a>
  </div>
  <div class="recipe-author">
    <span class="recipe-author-item">
      <i class="fas fa-user"></i>

      {% if recipe.author.first_name%}
        {{ recipe.author.first_name}}
      {% else%}
          {{ recipe.author.username}}
      {% endif %}

    </span>

    <span class="recipe-author-item">
      <i class="fas fa-calendar-alt"></i>
      {% comment %} {{ recipe.created_at/date:"d/m/Y" }} às  {% endcomment %}
      {{ recipe.created_at }}
      
    </span>

    <span class="recipe-author-item">
      <a href="{% url 'recipes:category' recipe.category.id%}">
        <i class="fas fa-layer-group"></i>
        <span>{{ recipe.category.name }}</span>
      </a>
    </span>
  </div>

  <div class="recipe-content">
    <p>
      {{ recipe.description }}
    </p>
  </div>

  <div class="recipe-meta-container">
    <div class="recipe-meta recipe-preparation">
      <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i>Preparo</h3>
      <div class="recipe-meta-text">
        {{ recipe.preparation_time }} {{ recipe.preparation_time_unit}}
      </div>
    </div>

    <div class="recipe-meta recipe-servings">
      <h3 class="recipe-meta-title">
        <i class="fas fa-pizza-slice"></i>Poções
      </h3>

      <div class="recipe-meta-text">{{recipe.servings}} {{recipe.servings_unit}}</div>
    </div>
  </div>


  {% if is_datail_page is not True%}
  <footer class="recipe-footer">
    <a href="{% url 'recipes:recipe' recipe.id %}" class="recipe-read-more button button-dark button full-width">
      <i class="fas fa-eye"></i>
      <span>Ver Mais!</span>
    </a>
  </footer>
  {% endif %}

  {% if is_datail_page is True%}
  <div class="preparation-steps" >
    {{recipe.preparation_steps}}
  </div>
  {% endif %}
</div>

recipes/templates/recipes/partials/search.html
<div class="search-container">
  <div class="container">
    <form action="#" class="search-form">
      <input type="search" name="search" class="search-input" />
      <button type="submit" class="search-button">
        <i class="fas fa-search"></i>
      </button>
    </form>
  </div>
</div>